### ISSUE TITLE
fatal error: 'emmintrin.h' file not found

### ISSUE THREAD

**Issue by subzeroDevelopment** [julianbei/alpine-opencv-microimage#1]
Im try to build an image of alpine-opencv but, I get this error
/opt/opencv-3.1.0/modules/core/include/opencv2/core/cvdef.h:168:12: fatal error: 'emmintrin.h' file not found

**Comment by julianbei** [comment]
which image do you try to build?
Python2 / Python3 ?

**Comment by subzeroDevelopment** [comment]
python2

**Comment by edmundkwok** [comment]
I'm getting this same error too on python2. Any luck getting it working again?

**Comment by julianbei** [comment]
Sorry for the late response.
I gonna investigate this.

**Comment by julianbei** [comment]
Ok I think the fix works now.
Lets see what the docker hub build says: https://hub.docker.com/r/julianbei/alpine-opencv-microimage/builds/

after all. you can use the `julianbei/alpine-opencv-microimage`as a starting point like this:

Dockerfile:
```
FROM julianbei/alpine-opencv-microimage
# your stuff
```

**Comment by julianbei** [comment]
@edmundkwok 
@subzeroDevelopment 
The build will go through. Please confirm.

**Comment by subzeroDevelopment** [comment]
@julianbei thank you for help and fix it.
now Dockerfile work.
